### PR TITLE
Show HR their interview section on calendar

### LINKED ISSUE #633: Show HR their interview section on calendar

### PR DESCRIPTION
**Pull request by Katrin-kudryash**
## PR includes

-   [x] Feature

## Related issues

Resolve #633

### CODE REVIEW

**Review by 9teen90nine — APPROVED** [review]

**Comment by Katrin-kudryash** [comment]
Untitled 11

**Comment by Katrin-kudryash** [comment]
qwerty

**Comment by tsumo** [comment]
Issue is about HR's, but code is about personal event exceptions. I don't understand

**Comment by Katrin-kudryash** [comment]
https://github.com/taskany-inc/hire/assets/81121562/b888d061-a6e7-4876-a151-4ff2ccf399ba

**Comment by Katrin-kudryash** [comment]
> Issue is about HR's, but code is about personal event exceptions. I don't understand

This is necessary so that HR employees have interview slots in their calendar that they have assigned

**Comment by tsumo** [comment]
> > Issue is about HR's, but code is about personal event exceptions. I don't understand
> 
> This is necessary so that HR employees have interview slots in their calendar that they have assigned

But where is check for HR role?

**Review by tsumo — APPROVED** [review]

**Comment by Katrin-kudryash** [comment]
> > > Issue is about HR's, but code is about personal event exceptions. I don't understand
> > 
> > 
> > This is necessary so that HR employees have interview slots in their calendar that they have assigned
> 
> But where is check for HR role?

accessChecks.calendar.readMany

**Pull request merged**
