### PR TITLE
Modal in calendar looks bad

### LINKED ISSUE #355: Modal in calendar looks bad
Try to add new section by calendar on free slot and you'll see this

image

### PR DESCRIPTION
**Pull request by Katrin-kudryash**
## PR includes

-   [x] Bug Fix

## Related issues

Resolve #355

### CODE REVIEW

**Comment by Katrin-kudryash** [comment]
c

**Comment by Katrin-kudryash** [comment]
x

**Comment by Katrin-kudryash** [comment]
Untitled5
Untitled

**Review by tsumo — APPROVED** [review]

**Review by nyet-ty — APPROVED** [review]

**Comment by Katrin-kudryash** [comment]
Untitled 6

**Pull request merged**
